# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

create table "products" (
  "name" VARCHAR NOT NULL,
  "cached_price" DECIMAL(21,2) NOT NULL,
  "photo" VARCHAR,
  "cached_average_rating" DOUBLE,
  "description" VARCHAR NOT NULL,
  "id" BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
)

# --- !Downs

drop table "people";
drop table "products";
